### ISSUE TITLE
I injected the dll but it doesnt work

### ISSUE THREAD

**Issue by zarzamateo** [Omega172/Crush-Crush-Cheat#10]
I used process hacker 2 as suggested in the blush blush cheat but when I inject the dll nothing happens when I press insert, and the dll is not in the modules of the process. I'm using the latest release and playing in the steam version. I also installed all dependecies.

**Comment by Breadoo-alt** [comment]
same here im having the same issue as him

**Comment by BoggyShlarfe** [comment]
Could you provide a better resource for how to use your program. I'm trying to learn how to hack unity games, but I am not doing very well. Its not seeming to function, could be user error, but I don't seem to be solitary in this.

**Comment by Omega172** [comment]
https://github.com/Omega172/Crush-Crush-Cheat/releases/tag/V.0.410
