### ISSUE TITLE
How to inject

### ISSUE THREAD

**Issue by Fujin33** [Omega172/Crush-Crush-Cheat#12]
Hello and thank you for your work,

I downloaded "Process hacker 2" from a site,
"win2_build.zip" and "source code.zip" on your github.
I extracted the zips to my desktop.
When I run process hacker 2 I go to Miscellaneous > inject DLL >

There I only find the file "\Win32_Build\Win32\Debug\DEBUG_Omegaware CrushCrush.dll"

When I launch it nothing happens, when I go into the game and hit "insert" nothing happens either.

Can you tell me the exact procedure to follow if I have made a mistake please? THANKS.

**Comment by RiritoNinigaya** [comment]
Try use Extreme Injector, not Process Hacker 2...

**Comment by mjbandroid** [comment]
add vidweo be good

**Comment by Fujin33** [comment]
![image](https://github.com/user-attachments/assets/e2b72805-3c59-44fa-9282-113551bb3667)

**Comment by RiritoNinigaya** [comment]
**try download Release version of this Cheat!!!**

**Comment by Omega172** [comment]
> **try download Release version of this Cheat!!!**

This, use the release DLL, there is a compiled release build provided.

Debug build is only for the people who know how to uses it and we're running into issues.

**Comment by Fujin33** [comment]
ok, I'm sorry, I feel like a bit of an idiot.

I was here:
https://github.com/Omega172/Crush-Crush-Cheat/releases/tag/V.0.410

I downloaded the 3 files just in case.

There are no other DLLs.

Can you do a quick tutorial? sorry but I'm really lost.

**Comment by RiritoNinigaya** [comment]
no... Sorry, I can't do a quick tutorial

**Comment by Fujin33** [comment]
Ok  And can you give me the position of the DLL because I did a search in my files and nothing except DEBUG.

**Comment by Omega172** [comment]
@Fujin33 
https://www.youtube.com/watch?v=4X9lxytX4ek
