### ISSUE TITLE
Windows flags the recent release as a trojan

### ISSUE THREAD

**Issue by krillini** [Omega172/Crush-Crush-Cheat#2]
If it isnt a virus could i get an explanation as to why i dont wanna risk it

**Comment by Omega172** [comment]
Well first of all this project is open source look through the code yourself. It is a standard internal cheat, it does things that Trojans and viruses would do like manipulate memory and hook functions.

https://www.virustotal.com/gui/file/26cdfe3d99abecf591ca19604d8207f5efa0be67e33be14c69362127a98ffc0d?nocache=1
If you look here it flags it as a game hack.

But simply put, if you don't trust it or don't want to risk it compile it yourself.
