### ISSUE TITLE
Where is the .dll file? Or how do I get it?

### ISSUE THREAD

**Issue by DaniloKko** [Omega172/Crush-Crush-Cheat#7]
I downloaded everything, and I don't get any .dll file, just a .sln file. I downloaded all the dependencies and restarted. Looked at every folder and no .dll, maybe I am asking a silly question because I was looking for a solution everywhere and Im the only one with this issue. So please, if anyone knows, please tell me, thank you.

**Comment by Kleker0** [comment]
Did you find it?

**Comment by Bursatman** [comment]
i cant find the dll too help me pls
