### ISSUE TITLE
Flawless, Could use another cheat though.

### ISSUE THREAD

**Issue by ghost** [Omega172/Crush-Crush-Cheat#8]
Works as expected but if possible could there be a cheat added to unlock the three jobs locked behind a paywall?
Otherwise diamonds, speed manipulator and instant phone message all work perfectly.

Thanks!
![image_2024-06-02_001017966](https://github.com/Omega172/Crush-Crush-Cheat/assets/103581639/3f519c2f-b48e-4631-a4db-99d50c2d21c5)

**Comment by Omega172** [comment]
As I said in https://github.com/Omega172/Crush-Crush-Cheat/issues/9 I just don't think it is possible or at least I have not found a way to do it yet.

There is some code that I thought might work in https://github.com/Omega172/Crush-Crush-Cheat/blob/main/OmegaWare%20Framework/Features/GiveStuff/GiveStuff.h but there is not class instances of `BlayFapInventory` to be able to pass as an argument to the `Invoke` method

**Comment by Omega172** [comment]
Surprise got it working 8332150613cd56e7b65238ec4d6cc861545ffa42
