### ISSUE TITLE
in-app purchases

### ISSUE THREAD

**Issue by ErrantYard** [Omega172/Crush-Crush-Cheat#9]
Can it be updated to have free in-app purchases or unlock the content within?(peanut dx date)

**Comment by Omega172** [comment]
This is an idea I explored but have not been able to do because after the game is initialized the `BlayFapInventory` object which is the class that handles the purchases and rewards has no instances to abuse

**Comment by Omega172** [comment]
Take a look 8332150613cd56e7b65238ec4d6cc861545ffa42
